### ISSUE TITLE
I would like to know the sigminer performance and use experience

### ISSUE THREAD

**Issue by ShixiangWang** [WuyangFF95/SynSigRun#1]
Dear @WuyangFF95,

I just find out that you are doing a benchmark work about mutational signature analysis tools. Could you add [sigminer](https://github.com/ShixiangWang/sigminer) to the list? I would like to know how it goes in your tests and also your feedback about the use experience of sigminer.

Best,
Shixiang

**Comment by WuyangFF95** [comment]
Dear Shixiang,

Sorry for the late reply! I added your work to my benchmarking study
already.

Best regards,
Wu Yang

Shixiang Wang <notifications@github.com> 于2020年10月19日周一 上午10:31写道：

**Comment by WuyangFF95** [comment]
It works well among 15 computational approaches, although not the best one.

Good luck to your PhD career!
Wu, Yang

武洋 <wuyangff95@gmail.com> 于2020年12月12日周六 上午8:41写道：

**Comment by ShixiangWang** [comment]
Thanks for your work :), I will close this issue now.
